[package]
name = "psa-update"
version = "0.0.3"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json", "stream", "gzip"] }
futures = "0.3"
futures-util = "0.3"
tokio = { version = "1", features = ["full"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

clap = "2.33"

log = "0.4"
env_logger = "0.9"

anyhow = "1.0"

console = "0.14"
dialoguer = "0.8"
indicatif = "0.17.0-beta.1"

regex = "1"

tar = "0.4.20"